### 1-5. Numpy는 Python에서 숫자 계산을 매우 빠르고 편하게 하기 위한 라이브러리다.
###### Numpy는 list에 비해서 속도가 매우 빠르기 때문에 딥러닝에서 많이 사용한다.
---

In [9]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)
print(type)

[1. 2. 3.]
<class 'type'>


In [14]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x+y)
print(x-y)
print(x*y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [24]:
# 넘파이의 N차원 배열
import numpy as np

A = ([[1, 3], [4, 5]])
print(A)


[[1, 3], [4, 5]]


In [ ]:
# 브로드캐스트: 행렬이 다른 두 배열끼리 계산하여 행렬이 맞춰지는 것.
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A*B)

[[10 40]
 [30 80]]


In [35]:
import numpy as np

X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0])

for row in X:
    print(row)

X = X.flatten()
print(X)
X[np.array([0, 2, 4])]

print(X>15)
print(X[X>15])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]
[ True  True False  True False False]
[51 55 19]
