#### **모두를 위한 딥러닝**
slide
https://drive.google.com/drive/folders/1qVcF8-tx9LexdDT-IY6qOnHc8ekDoL03

git
https://github.com/deeplearningzerotoall/PyTorch?tab=readme-ov-file

youtube
https://www.youtube.com/watch?v=7eldOrjQVi0&list=PLQ28Nx3M4JrhkqBVIXg-i5_CVVoS1UzAv


---

#### **Tensor**

**batch size = 세로** <br>
**wide,length = 가로**

1. 2D Tensor

- 주로 MLP의 입력이나 Simple Linear Regression에 사용

- (Batch Size, Figure Size)
- $[ \text{B}, \text{F} ]$



2. 3D Tensor 

- [CV] 이미지 데이터를 다룰 때 주로 사용 (Channel-First)
    - [$batch ,width ,height$]
- [NLP] 자연어 처리 주로
    - [$batch ,length ,dim$]

3. 3D Tensor

- 이미지 데이터를 다룰 때 주로 사용 (Channel-First)


- (Batch Size, Channels, Height, Width)
- $B \times C \times H \times W$

In [5]:
import torch
import numpy as np

print('PyTorch is just like NumPy - 1D')
print('-------------------------------')

ft = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(ft)
print(ft.dim())  # rank
print(ft.shape)  # shape
print(ft.size()) # shape
print(ft[0], ft[1], ft[-1]) # Element
print(ft[2:5], ft[4:-1])    # Slicing
print(ft[:2], ft[3:])       # Slicing



PyTorch is just like NumPy - 1D
-------------------------------
tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [7]:
# Broadcasting
m1 = torch.FloatTensor([[3, 3]])  #1x2 mat
m2 = torch.FloatTensor(([2, 2]))
print(m1 + m2)

m1 = torch.FloatTensor([[1, 2]])  #1x2 mat
m2 = torch.FloatTensor([2])  # scalar-> 1x2 mat (Broadcasting)
print(m1 + m2)

m1 = torch.FloatTensor([[1, 2]])  #1x2 mat -> 2x2 mat  (Broadcasting)
m2 = torch.FloatTensor([2, 4])  # 2x1 mat -> 2x2 mat   (Broadcasting)
print(m1 + m2)

tensor([[5., 5.]])
tensor([[3., 4.]])


In [9]:
# Matrix Multiplication (내적) -> `matmul`
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1 (행렬곱)

# elemnet-wise Multiplication -> `mul`
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[10], [100]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 10.,  20.],
        [300., 400.]])
tensor([[ 10.,  20.],
        [300., 400.]])


In [11]:
# Mean (평균) - 1D
t = torch.FloatTensor([1, 2])
print(t.mean())

# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

print()
print('---------')
print('Mean - 2D')
print('---------')
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.mean())
print(t.mean(dim=0)) #세로행 mean
print(t.mean(dim=1)) # 가로행 Mean
print(t.mean(dim=-1)) # 마지막행=가로행 Mean


tensor(1.5000)
Can only calculate the mean of floating types. Got Long instead.

---------
Mean - 2D
---------
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [12]:
# sum
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())
print(t.sum(dim=0)) # 세로행 sum
print(t.sum(dim=1)) # 가로행
print(t.sum(dim=-1)) # 마지막행=가로행

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [13]:
# max(최댓값), Argmax(최댓값의 위치 반환)
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max(index=0) and argmax(index=1)
print('Max: ', t.max(dim=0)[0])    # max(index=0)
print('Argmax: ', t.max(dim=0)[1]) # argmax(index=1)

print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
(tensor([3., 4.]), tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
(tensor([2., 4.]), tensor([1, 1]))
(tensor([2., 4.]), tensor([1, 1]))


In [15]:
# View(Reshape) 중요
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)   # 2x2x3 mat

# -1이 들어간 dim은 자동 결정시킴
print(ft.view([-1, 3]))     # 2x2x3 mat -> 4x3 mat
print(ft.view([-1, 3]).shape)

print(ft.view([-1, 1, 3])) # 1,2 dim은 1,3차원으로 0dim은 자동으로해봐
print(ft.view([-1, 1, 3]).shape) # -> 4x1x3 mat

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [16]:
# Squeeze (`차원 제거`를 통해 개수를 맞추기 위해 사용)
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape) # 3x1 mat

print(ft.squeeze())  # 3x1 -> (3,)
print(ft.squeeze().shape) # dim 1 제거

# Unsqueeze (차원 추가)
ft = torch.Tensor([0, 1, 2])
print(ft.shape) # (3,)

print(ft.unsqueeze(0))  # 0번째(맨앞)에 차원 추가
print(ft.unsqueeze(0).shape) # (3,) -> 1x3 mat

print(ft.unsqueeze(1)) # 1번째(뒤)에 차원 추가
print(ft.unsqueeze(1).shape) # (3,) -> 3x1 mat

print(ft.unsqueeze(-1))  # 마지막 = 1번째(뒤)
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [17]:
# Scatter (One-hot Encoding)
# one-hot encoding = 하나만 1이고 나머지 0 (loss구할때 정답label처리시 썼었음)
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt) # 4x1 mat

one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
# lt -> 0번은 0에, 1번 행은 1에 ~~...
one_hot.scatter_(1, lt, 1) # scatter(dim=1(가로방향), lt(인덱스위치), 1채워라)
print(one_hot)

tensor([[0],
        [1],
        [2],
        [0]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


In [18]:
# Casting (타입 변환)
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt) 
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [19]:
# Concatenate (붙이기)
x = torch.FloatTensor([[1,2], [3, 4]])
y = torch.FloatTensor([[5,6], [7, 8]])

print(torch.cat([x,y], dim = 0))
print(torch.cat([x,y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [20]:
# Stacking (Concatenate를 편하게)

In [21]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [22]:
# ones and zeros (모양 본뜨기)
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
# zip (병렬반복) -> 데어티와 정답 레이블을 쌍으로 묶어 처리할 때 사용
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9


#### In-place Operation
scatter_ 처럼 함수 이름 뒤에 **언더바(_)**가 붙으면 In-place 연산이라고 해서, 새로운 텐서를 만드는 게 아니라 자기 자신을 직접 수정합니다. 메모리를 아낄 수 있죠!

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])

print(t.mul(2.))
print(t)

print(t.mul_(2.))  # in-place operation
print(t)


tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
