##### **1.5.1 Numpy 불러오기**
Numpy는 외부 라이브러리로 import 해서 사용해야한다.

In [2]:
import numpy as np

##### **1.5.2 Numpy 배열 생성하기**

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)  # [1. 2. 3.]
print(type(x))  # <class 'numpy.ndarray'>

[1. 2. 3.]
<class 'numpy.ndarray'>


##### **1.5.3 Numpy 산술 연산**

- 연산 하는 두 array의 요소 수가 같아야 한다.
- 원소 별(element-wise) Product :  (원소별 곱셈)

In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)  # 원소별(element-wise) 덧셈
print(x - y)
print(x * y)  # 원소별 곱셈(element-wise product)
print(x / y)
print(x / 2.0)  # [ 0.5  1.   1.5]

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


##### **1.5.4 Numpy N차원 배열 & Broadcasting**

- Broadcast : 형상이 다른 배열끼리의 연산을 스마트하게 해줌. 
- 행렬곱이 아님! 
- `*` 는 element-wise 곱하기 하는 연산


- 행렬 곱은 `@`사용 (np.dot도 가능)

In [ ]:
A = np.array([[1, 2], [3, 4]])  # 2x2 Matrix
B = np.array([10, 20])
print(A * B)

[[10 40]
 [30 80]]


##### **1.5.6 원소 접근**

- 원소 인덱스는 0부터 시작
- for문으로도 각 원소에 접근 가능

In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
'''
[[51 55]
 [14 19]
 [ 0  4]]
 '''
print(X[0])  # [51 55] (행 전체)
print(X[0][1])  # 55 (1행 2열)
for row in X:
    print(row)

X = X.flatten()  # X를 1차원 배열로 변환(평탄화)
print(X)  # [51 55 14 19  0  4]
print(X[np.array([0, 2, 4])])  # 인덱스가 0,2,4인 원소 얻기 [51 14  0]
print(X > 15)  # [ True  True False  True False False]
print(X[X > 15])  # [51 55 19]

[[51 55]
 [14 19]
 [ 0  4]]
51
55
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]
[51 14  0]
[ True  True False  True False False]
[51 55 19]
